### ISSUE TITLE
Lokc\Unlock

### ISSUE THREAD

**Issue by s235711** [gechu/unofficial-danalock-web-api#1]
Hi, I managed to retrieve the state. thank you very much.
Now i'm trying to use the lock operation in /bridge/v1/execute.
My json look like this
{
  "device": "xx:xx:xx:xx",
  "operation": "afi.lock.get-state",
  "argument": ["lock"]
}
But all i get in return is the Jobid without any operation

**Comment by erikwihlborg76** [comment]
Hi! When locking the lock, the operation should be "afi.lock.operate" - the OpenAPI doc danabridge API was wrong but has been fixed now. 

Can you get it working now?

**Comment by s235711** [comment]
Yes, Thank you!
