### ISSUE TITLE
None HA user.

### ISSUE THREAD

**Issue by dezral** [gechu/unofficial-danalock-web-api#2]
Could you give me an example in like postman og curl?

**Comment by erikwihlborg76** [comment]
Hi @dezral  - First you have to implement support for OAuth2, then a requst may look like this in concept to trigger a locking of your Danalock

**Set message headers:**
content-type = "application/json"
Accept  "application/json"
Authorization = "Bearer -your access token-"

**Set HTTP operation & URL**
method = "POST";
url = "https://bridge.danalockservices.com/bridge/v1/execute";

**Finally, set message payload:**
payload = {"device": <bluetooth address>,"operation":"afi.lock.operate","arguments":["lock"]};

I the near future I plan to upload a node-red implementation where you could see how to create calls towards the Danalock APIs

**Comment by vandenbrakel** [comment]
Did you get it to work in Postman? Trying to test it. As IFTTT support is still lacking. Also starting to use Postman for the first time, so just getting into it.

**Comment by erikwihlborg76** [comment]
Postman is defintently worth learning! However, I have no plans to provide a postman collection of the calls required to make use of the API. I've done major changes to the node-red implementation of the Danalock APIs that I personally use, and may share it if it works out good.

**Comment by erikwihlborg76** [comment]
Closing
