### ISSUE TITLE
(rather off topic) danalock without proprietary web access?

### ISSUE THREAD

**Issue by markvdb** [gechu/unofficial-danalock-web-api#3]
Hello,

I'm looking for something like danalock, with a few obvious extra conditions:
- no manufacturer remote control over access to my home
- wired FOSS home automation system integration and/or decent API docs (home assistant, domoticz, openhab, whatever)
- keypad
- no batteries
- fits an existing exterior door

Sorry for polluting your issue tracker with this only tangentially related request. It looks as if what I want does not exist. I'd be grateful for any relevant ideas.

Kind regards,

Mark

**Comment by erikwihlborg76** [comment]
Hi Mark! You have a very fine list of requirements - that would be the ultimate lock. Unfortunately, I have not come across a lock that would satisfy all of those requirements, yet.

In Sweden, at least in the past, the only lock that was approved by an authority that certified locks ([SSF](https://sv.wikipedia.org/wiki/SSF_St%C3%B6ldskyddsf%C3%B6reningen))- sometimes required by insurance companies, was Yale doorman. I have experience from Yale doorman v2 (version 3 is in the makings). It is a much more solid solution compared to Danalock, it simply always works - and you get the keypad out of the box. Runs on battery though, and to get smartness out of it, you have to connect it to a proprietary hub from, what I'm aware, is available from at least two different manufactures  - which may remove it from your list. But the lock, via one of these proprietary hubs, has integration to for example home assistant.

Let me know if you find something useful, kind regards, Erik

**Comment by markvdb** [comment]
The closest I've found is a simple electromechanical lock like https://www.perco.com/products/lbp85.1-mortise-electromechanical-lock.php . That should be easy to integrate into my FOSS home automation system.

I am getting new windows and doors installed anyway, but my supplier doesn't offer installation of custom locking mechanisms like this. Maybe I should order just the windows from him, and a new custom front door somewhere else...

Alternatively, the closest I got until now was Nuki:
- integrate into home automation using one of:
  - LAN mode: https://developer.nuki.io/t/bridge-http-api/26 (would obviously need blocking outgoing traffic at the VLAN level). This approach is limited because the http bridge does not have admin access to all the bluetooth lock's features.
  - Bluetooth mode without the http bridge: https://developer.nuki.io/page/nuki-smart-lock-api-210/2#heading--authorize-app
- add a fake battery AC adapter to the lock itself, or use their upcoming battery thingie

**Comment by erikwihlborg76** [comment]
Similar to one of the cases you describe, a user in this project´s [home-assistant thread](https://community.home-assistant.io/t/unoffical-danalock-web-api/238097) looked briefly into making calls directly to the danabridge´s API (and not via the vendors API endpoints). No success so far though, not sure he's working on it anymore.

**Comment by erikwihlborg76** [comment]
House cleaning
